#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/naissancedb
#    username: postgres
#    password: sire
#    driver-class-name: org.postgresql.Driver
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

#Configuration pour mysql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_naissance_db
    username: root
    password: sire
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




